<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ4PJP3x\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ4PJP3x/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ4PJP3x.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ4PJP3x\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZ4PJP3x\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Z4PJP3x',
    'container.build_id' => 'd7d20152',
    'container.build_time' => 1557655257,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ4PJP3x');
